In [1]:
from __future__ import division
from numpy.random import randn
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
plt.rc('figure', figsize=(12, 5))
np.set_printoptions(precision=4)
%pwd
plt.rcParams['font.sans-serif']=['SimHei']#中文标签

In [2]:
#path='./itchat_data.csv'

In [3]:
path='./2017MBA-N.csv'

In [4]:
columns = ['RemarkName', 'sex', 'births','NickName']

In [5]:
frame = pd.read_csv(path,encoding='utf-8')

In [6]:
fr1=frame.reindex(columns=['RemarkName','NickName','Sex','Province','City'])

In [7]:
fr1.groupby(['Province','City']).count()

                            RemarkName  NickName  Sex
Province        City
Queensland      Gold Coast           0         1    1
South Australia Whyalla              0         1    1
内蒙古             包头                   0         1    1
北京              东城                   2        10   10
                丰台                   0        13   13
                大兴                   0         5    5
                延庆                   0         1    1
                房山                   0         2    2
                昌平                   1        11   11
                朝阳                   5        79   79
                海淀                   5        79   79
                石景山                  0         2    2
                西城                   2        20   20
                通州                   0         6    6
                门头沟                  0         1    1
                顺义                   0        10   10
吉林              长春                   0         1    1
天津              和平                   0         1    1
                河东                   0         1    1
山东              烟台                   0         1    1
                青岛                   0         2    2
新疆              乌鲁木齐                 0         1    1
江苏              南通                   1         1    1
                徐州                   0         1    1
江西              萍乡                   0         1    1
河北              张家口                  0         1    1
                石家庄                  0         2    2
                秦皇岛                  0         1    1
河南              郑州                   0         2    2
浙江              温州                   0         1    1
湖南              衡阳                   0         1    1
福建              厦门                   0         1    1
辽宁              大连                   0         1    1
                沈阳                   0         1    1
陕西              西安                   0         3    3
黑龙江             哈尔滨                  1         1    1

In [8]:
#fr2=fr1.groupby(['Province','City']).count().unstack().plot(kind='bar',figsize=(10,5),stacked=True)

In [9]:
#plt.show()

In [10]:
fr1[fr1['Province'].isnull()].count()

RemarkName     5
NickName      47
Sex           47
Province       0
City           0
dtype: int64